services:
  kuka-1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kuka_connector_kuka-1
    env_file: .env
    environment:
      - ROBOT_ID=kuka-1
      - CONFIG_FILE=/config/fleet.yaml
      - LOG_LEVEL=DEBUG
    volumes:
      - ./config/my_fleet.yaml:/config/fleet.yaml:ro
    network_mode: host
    restart: "no"
