# SPDX-FileCopyrightText: 2026 InOrbit, Inc.
#
# SPDX-License-Identifier: MIT

services:
  kuka-local-test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kuka_connector_local-test
    env_file: .env
    environment:
      - ROBOT_ID=kuka-local-test
      - CONFIG_FILE=/config/fleet.yaml
      - LOG_LEVEL=DEBUG
    volumes:
      - ./config/my_fleet.yaml:/config/fleet.yaml:ro
      - ./config/kuka_nodes.json:/config/kuka_nodes.json:ro
    network_mode: host
    restart: "no"
